name: Build executables on release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install `uv`
        uses: astral-sh/setup-uv@v6.0.1
        with:
          version: "0.8.17"

      - name: Set version
        shell: bash
        run: echo "VERSION=$(uvx hatch version | sed -r 's/^([[:digit:]]+(\.[[:digit:]]+){1,3}).*$/\1/')" >> "$GITHUB_ENV"

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13.2"

      - name: Install requirements
        run: uv sync --all-extras --frozen

      - name: Build executable
        run: >
          uv run nuitka
          --product-name="mafolex"
          --product-version=${{ env.VERSION }}
          --file-description="mafolex"
          --copyright="2025 Theo Court. Licensed under the Mozilla Public License v2.0."
          --enable-plugin=pyside6
          --onefile
          --assume-yes-for-downloads
          --python-flag=-m
          ./src/mafolex

      - name: Upload Artifacts (Linux)
        uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'Linux' }}
        with:
          name: Build for Linux
          path: mafolex.bin
          compression-level: 0
      
      - name: Upload Artifacts (Windows)
        uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'Windows' }}
        with:
          name: Build for Windows
          path: mafolex.exe
          compression-level: 0

      - name: Add to release (Linux)
        if: ${{ github.event_name == 'release' && runner.os == 'Linux' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} mafolex.bin

      - name: Add to release (Windows)
        if: ${{ github.event_name == 'release' && runner.os == 'Windows' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} mafolex.exe
